[package]
name = "the_online_atlas_rust_lib"
edition = "2021"
rust-version = "1.77.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
glam = "0.27.0"

[dependencies.web-sys]
version = "0.3.69"
features = ["console"]

[profile.release]
lto = true
opt-level = "s"
